name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: windows-latest

    env:
      CONTENT_ROOT_PATH: ${{ github.workspace }}/apiGerencia

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore apiGerencia.sln
      working-directory: ${{ github.workspace }}/apiGerencia

    - name: Build the Solution
      run: msbuild apiGerencia.sln /p:Configuration=Release
      working-directory: ${{ github.workspace }}/apiGerencia

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ github.workspace }}/apiGerencia
